#!/bin/bash
pushd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1

if [[ ! -x node_modules/.bin/npm-which ]] ; then
	if [[ ! -x "$(which npm)" ]] ; then
		echo "no npm found, can't continue" >&2

		popd >/dev/null 2>&1

		exit 1
	fi

	echo "looks like you need to run npm install. i'll take care of it."

	"$(which npm)" install

	if [[ ! -x node_modules/.bin/npm-which ]] ; then
		echo "npm install didn't setup node_modules/.bin correctly." >&2
		echo "you might need to delete node_modules and run npm install again" >&2
		exit 3
	fi
fi

GULP="$(node_modules/.bin/npm-which gulp 2>&1)"

if [[ "${GULP}" == "gulp not found" ]] ; then
	if [[ -x "$(which npm)" ]] ; then
		echo "no gulp found, installing..." >&2
		"$(which npm)" install gulp
	fi

	GULP="$(node_modules/.bin/npm-which gulp 2>&1)"

	if [[ "${GULP}" == "gulp not found" ]] ; then
		echo "still no gulp found, exiting" >&2

		popd >/dev/null 2>&1

		exit 2
	fi
fi

${GULP} $@

popd >/dev/null 2>&1
